-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 14, 2024 at 07:00 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `product-1`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `image` varchar(50) NOT NULL,
  `title` varchar(300) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `description` varchar(1000) NOT NULL,
  `category` varchar(50) NOT NULL,
  `date` date NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `image`, `title`, `price`, `description`, `category`, `date`) VALUES
(1, 'headphone.png', 'Dark Head Phone', 50.23, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione expedita distinctio culpa alias qui facilis quia, quos maxime tenetur ipsa! Dolore voluptas veniam harum cum provident eaque odit neque illo.', 'Headphones', '2024-06-23'),
(2, 'andriod-smart-watch.jpg', 'Andriod Smart Watch', 15.24, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus fuga omnis repellendus earum. Aliquam, eaque quibusdam temporibus voluptatum ullam expedita adipisci tenetur distinctio dolores aperiam iste iure, porro autem exercitationem nesciunt consequatur molestiae. Et doloremque mollitia, corporis dolor esse iste aspernatur odit vitae aliquam cum sequi neque veritatis tempore natus quo nihil distinctio deserunt tenetur vel harum provident id exercitationem. Ab natus provident sint fugit eveniet similique sit accusantium quam et repudiandae earum culpa fugiat aut in quae, temporibus neque facere cupiditate a nemo, eaque unde! Aperiam eveniet labore beatae! Magnam, nobis expedita, cumque perspiciatis, dolores omnis excepturi vitae similique sint optio ea quis? Nemo quo error quasi velit dolorem ipsum quam praesentium eligendi tempora cumque accusamus sed vero, laborum blanditiis sit inventore dicta voluptatibus nesciunt voluptate, consequuntur deserunt? Asperiores, incidunt eum! Deser', 'Watches', '2024-06-23'),
(3, 'artOfNotGivingAFuck.jpeg', 'Art Of Not Giving A fuck', 12.22, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus fuga omnis repellendus earum. Aliquam, eaque quibusdam temporibus voluptatum ullam expedita adipisci tenetur distinctio dolores aperiam iste iure, porro autem exercitationem nesciunt consequatur molestiae. Et doloremque mollitia, corporis dolor esse iste aspernatur odit vitae aliquam cum sequi neque veritatis tempore natus quo nihil distinctio deserunt tenetur vel harum provident id exercitationem. Ab natus provident sint fugit eveniet similique sit accusantium quam et repudiandae earum culpa fugiat aut in quae, temporibus neque facere cupiditate a nemo, eaque unde! Aperiam eveniet labore beatae! Magnam, nobis expedita, cumque perspiciatis, dolores omnis excepturi vitae similique sint optio ea quis? Nemo quo error quasi velit dolorem ipsum quam praesentium eligendi tempora cumque accusamus sed vero, laborum blanditiis sit inventore dicta voluptatibus nesciunt voluptate, consequuntur deserunt? Asperiores, incidunt eum! Deser', 'Books', '2024-06-23'),
(4, 'artofwar.jpeg', 'Art Of War', 15.24, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo, consectetur eius? Voluptas consequatur, officia soluta error aperiam dolore pariatur et laudantium commodi illo ea nisi voluptates, similique tenetur illum expedita, recusandae quo in impedit ipsam a fugiat cupiditate veritatis ex! Optio, voluptate sunt numquam pariatur nemo consectetur distinctio cupiditate, molestiae dolores repellendus reiciendis eos? Quis minima veniam, maiores ea, temporibus dolore similique ratione dignissimos, saepe esse voluptates numquam commodi? Nam officiis dignissimos beatae, numquam earum odio, doloribus accusamus similique recusandae placeat atque repudiandae fugiat repellendus sint ad iure deserunt hic dolores distinctio architecto eligendi dolor at. Ipsa, excepturi non. Ad ipsam, modi doloremque, magni velit commodi facere sequi minima laboriosam, reiciendis corrupti impedit minus dolor nostrum accusamus autem a aut? Similique, optio nesciunt? Cumque necessitatibus sunt iste esse eos providen', 'Books', '2024-06-23'),
(5, 'call-of-duty-mwf3.jpg', 'Call Of Duty - Modern War Fare', 15.40, ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo, consectetur eius? Voluptas consequatur, officia soluta error aperiam dolore pariatur et laudantium commodi illo ea nisi voluptates, similique tenetur illum expedita, recusandae quo in impedit ipsam a fugiat cupiditate veritatis ex! Optio, voluptate sunt numquam pariatur nemo consectetur distinctio cupiditate, molestiae dolores repellendus reiciendis eos? Quis minima veniam, maiores ea, temporibus dolore similique ratione dignissimos, saepe esse voluptates numquam commodi? Nam officiis dignissimos beatae, numquam earum odio, doloribus accusamus similique recusandae placeat atque repudiandae fugiat repellendus sint ad iure deserunt hic dolores distinctio architecto eligendi dolor at. Ipsa, excepturi non. Ad ipsam, modi doloremque, magni velit commodi facere sequi minima laboriosam, reiciendis corrupti impedit minus dolor nostrum accusamus autem a aut? Similique, optio nesciunt? Cumque necessitatibus sunt iste esse eos provide', 'Games', '2024-06-23'),
(6, 'e-football24.jpg', 'E-Football 2024', 12.34, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo, consectetur eius? Voluptas consequatur, officia soluta error aperiam dolore pariatur et laudantium commodi illo ea nisi voluptates, similique tenetur illum expedita, recusandae quo in impedit ipsam a fugiat cupiditate veritatis ex! Optio, voluptate sunt numquam pariatur nemo consectetur distinctio cupiditate, molestiae dolores repellendus reiciendis eos? Quis minima veniam, maiores ea, temporibus dolore similique ratione dignissimos, saepe esse voluptates numquam commodi? Nam officiis dignissimos beatae, numquam earum odio, doloribus accusamus similique recusandae placeat atque repudiandae fugiat repellendus sint ad iure deserunt hic dolores distinctio architecto eligendi dolor at. Ipsa, excepturi non. Ad ipsam, modi doloremque, magni velit commodi facere sequi minima laboriosam, reiciendis corrupti impedit minus dolor nostrum accusamus autem a aut? Similique, optio nesciunt? Cumque necessitatibus sunt iste esse eos providen', 'Games', '2024-06-23'),
(7, 'fc24.jpg', 'EA FC24', 10.23, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Numquam excepturi enim voluptatum consectetur quos modi, velit natus nemo architecto et officiis ducimus, nesciunt nobis, culpa facilis! Quos, iste consectetur sit error aliquid pariatur tempore nam qui, doloremque facilis magnam id doloribus reprehenderit dicta. Molestiae eveniet explicabo, impedit voluptas sit nobis minus iure, a unde aliquam alias corporis dignissimos animi! Sunt aperiam adipisci delectus ea sint recusandae veniam iste facilis rerum magni vitae possimus ad esse, consectetur, maiores officiis dignissimos illum autem soluta non perspiciatis voluptates magnam enim. Ad ratione aliquam quisquam ducimus sed! Commodi, dolor. Quo possimus incidunt eligendi corporis laborum laboriosam? Sapiente iste alias consectetur nisi ratione unde? Eius, molestiae illum, magni labore obcaecati dicta consectetur dignissimos quaerat ea aliquam culpa tempore, rerum dolore soluta consequuntur beatae vel voluptates. Esse perspiciatis d', 'Games', '2024-06-23'),
(8, 'generic-T55.jpg', 'Generic-T55', 130.22, '    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Numquam excepturi enim voluptatum consectetur quos modi, velit natus nemo architecto et officiis ducimus, nesciunt nobis, culpa facilis! Quos, iste consectetur sit error aliquid pariatur tempore nam qui, doloremque facilis magnam id doloribus reprehenderit dicta. Molestiae eveniet explicabo, impedit voluptas sit nobis minus iure, a unde aliquam alias corporis dignissimos animi! Sunt aperiam adipisci delectus ea sint recusandae veniam iste facilis rerum magni vitae possimus ad esse, consectetur, maiores officiis dignissimos illum autem soluta non perspiciatis voluptates magnam enim. Ad ratione aliquam quisquam ducimus sed! Commodi, dolor. Quo possimus incidunt eligendi corporis laborum laboriosam? Sapiente iste alias consectetur nisi ratione unde? Eius, molestiae illum, magni labore obcaecati dicta consectetur dignissimos quaerat ea aliquam culpa tempore, rerum dolore soluta consequuntur beatae vel voluptates. Esse perspiciat', 'Watches', '2024-06-23'),
(9, 'gold-watch.jpg', 'Gold Watch', 110.22, 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Labore, distinctio. Expedita et debitis qui. Beatae accusamus recusandae repellat reprehenderit. Dolor sequi rem perferendis impedit libero sed suscipit, vero voluptate, natus voluptatibus ullam odit aliquid dolore molestias voluptatem sint blanditiis reiciendis quis? Inventore laudantium ipsa molestiae corporis temporibus dolorum minima! Qui natus aperiam sint, aut expedita rerum possimus quia ipsa suscipit voluptatibus officia eligendi, provident molestiae pariatur molestias. Mollitia dolore nobis assumenda! Repellendus corrupti facilis quia voluptas illo, sapiente qui sequi voluptates quo eius sed odit. Facilis perferendis dolores ullam iure, quaerat, eum veniam fuga fugit ducimus perspiciatis provident, corporis numquam ab quia in quas fugiat repudiandae deserunt nam non quisquam. Quod saepe eaque repellat nulla, corporis, hic consequatur molestias excepturi doloribus esse dicta accusantium commodi quaerat facilis assumenda ', 'Watches', '2024-06-23'),
(10, 'HP-Spectre-2023.jpeg', 'HP Spectre 2023', 200.22, 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Labore, distinctio. Expedita et debitis qui. Beatae accusamus recusandae repellat reprehenderit. Dolor sequi rem perferendis impedit libero sed suscipit, vero voluptate, natus voluptatibus ullam odit aliquid dolore molestias voluptatem sint blanditiis reiciendis quis? Inventore laudantium ipsa molestiae corporis temporibus dolorum minima! Qui natus aperiam sint, aut expedita rerum possimus quia ipsa suscipit voluptatibus officia eligendi, provident molestiae pariatur molestias. Mollitia dolore nobis assumenda! Repellendus corrupti facilis quia voluptas illo, sapiente qui sequi voluptates quo eius sed odit. Facilis perferendis dolores ullam iure, quaerat, eum veniam fuga fugit ducimus perspiciatis provident, corporis numquam ab quia in quas fugiat repudiandae deserunt nam non quisquam. Quod saepe eaque repellat nulla, corporis, hic consequatur molestias excepturi doloribus esse dicta accusantium commodi quaerat facilis assumenda ', 'Laptops', '2024-06-23'),
(11, 'iphone8.jpeg', 'Iphone 8', 1220.22, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis ratione, soluta quasi nisi exercitationem nostrum, reiciendis totam, repellat maiores porro hic quae voluptatem beatae eius explicabo aliquam eum ut nesciunt a necessitatibus id! Architecto aut distinctio soluta, vero sunt veritatis? Beatae corporis eum tempore vitae totam, et eligendi nemo id est placeat ea ratione minima ipsa. Sunt quisquam assumenda, alias architecto, cumque iste culpa ab, ad tempora vitae distinctio. Quas aut nihil asperiores laudantium blanditiis fugit, temporibus totam veniam voluptate libero ea accusantium ipsam expedita tempora dignissimos quaerat voluptatum quam sunt itaque numquam, amet nisi. Dolorum voluptas fugiat nemo. Officiis harum optio autem, sequi sint excepturi maiores architecto adipisci. Necessitatibus velit doloremque unde sed aspernatur fugiat, neque amet nemo laborum ab hic, dolores in incidunt dolor enim illo! Dolor voluptas alias doloremque non sed est mollitia culpa quae? Natus', 'Phones', '2024-06-23'),
(12, 'iphone11.jpg', 'Iphone 11', 1500.22, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sunt nesciunt repellat facere reprehenderit nostrum reiciendis dignissimos amet culpa sequi eaque molestias distinctio exercitationem eum cum sed dicta quibusdam tenetur veniam facilis inventore possimus ex accusantium, saepe minus. Minus, suscipit eius nemo est aspernatur sequi earum labore nam at consequuntur sunt. Officiis maiores qui non autem tempora obcaecati quis odit quia, ullam velit esse fugit sequi earum labore odio consectetur nesciunt excepturi! Ratione officia, maiores harum maxime dolorem, facilis, dolore error veniam modi quis aspernatur cupiditate. Quisquam totam eveniet ex temporibus magnam repellendus at, itaque aut odio optio consectetur nisi. Eos, aliquid dolores? Pariatur aliquam deserunt error ea animi ducimus nisi, explicabo tempora vero, dolores nesciunt cum voluptatibus consectetur tenetur harum! Qui iste soluta voluptate eaque officia delectus commodi sint, magnam ipsa esse facere obcaecati nostrum fug', 'Phones', '2024-06-23'),
(13, 'iphone12.jpeg', 'Iphone 12', 2110.22, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus exercitationem dolor nihil, distinctio quas nemo cum ab eaque voluptatem, adipisci in consectetur excepturi vero expedita soluta nam? Repellendus, reprehenderit sapiente. Voluptate ex laudantium inventore maiores impedit cumque. Cumque ratione eaque temporibus blanditiis explicabo quo ullam nulla obcaecati corporis architecto ipsum, minima magni voluptatum, commodi tempora, voluptate nemo consectetur enim harum ipsam quas. Voluptate debitis, odio ipsam animi corporis maxime autem esse mollitia qui doloribus soluta ad velit dignissimos totam recusandae quas sunt suscipit ipsa ducimus. Unde hic laboriosam, dolor quas, a culpa voluptate, necessitatibus sit veritatis doloremque est. Doloremque, nobis ipsam dolor voluptas dignissimos possimus natus beatae doloribus, voluptates sit nulla. Quod quae quam nobis omnis saepe, eum quos molestias perspiciatis. Ipsum dignissimos nemo aliquid. Dolor, molestias harum porro obcaecat', 'Phones', '2024-06-23'),
(14, 'macbook2022.jpeg', 'Macbook 2022', 3200.22, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id quisquam eos vero alias voluptatum blanditiis modi dolorem aspernatur libero, saepe vitae ea veritatis ex nihil laboriosam? Aliquid necessitatibus corrupti provident, quisquam nesciunt autem neque quam, dolor suscipit similique, iste consequatur rem odit sit alias. Amet a rerum quaerat, quis voluptatum fuga non iste unde laborum doloribus, commodi vel deleniti ab iure ipsum omnis asperiores voluptate quos reiciendis nulla eligendi, ut facere neque aliquid! Praesentium repudiandae corporis quasi harum est voluptatibus dolore quae ad sunt modi debitis doloribus, ex obcaecati molestias laborum ea ullam odit doloremque voluptatum, tempore minima et vel. A laboriosam fugit recusandae accusantium quia nam voluptatum officiis, quod esse id, sit facere consectetur aliquid nostrum explicabo repellendus quos. Sunt, quibusdam, placeat alias accusamus accusantium doloremque amet consequuntur labore sed autem quisquam quaerat voluptatibus', 'Laptops', '2024-06-23'),
(15, 'macbook2023.jpg', 'Macbook-2023', 3250.50, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium deleniti excepturi veritatis quibusdam debitis, provident modi. Optio cumque consectetur nobis repudiandae, ad ratione quibusdam qui possimus dolorem inventore iure cupiditate dolores, nemo repellendus unde repellat, facilis amet a labore mollitia. Iure quis recusandae voluptatem dignissimos, unde non nesciunt modi nostrum labore reprehenderit architecto repellat corporis facilis quam harum. Reprehenderit eius odit enim doloremque distinctio ad atque nisi id! Laborum asperiores, beatae eius sunt quae nam a quia quod distinctio cupiditate dolor qui totam pariatur neque recusandae illo soluta sequi ex nostrum error id sed velit! Dolor sequi qui a distinctio consequatur neque, aliquam molestias laborum voluptas aliquid et! Voluptatibus excepturi porro atque, enim blanditiis in ullam tempora, nihil cum, quos assumenda odit dolorum quaerat. Repellendus asperiores eius, voluptates adipisci odio officiis ipsam aliquam laborum', 'Laptops', '2024-06-23'),
(16, 'marvels-avengers.jpeg', 'Marvel Avengers', 70.34, 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatem at quia architecto eius ullam reprehenderit nesciunt unde nostrum atque magni. Deleniti aut possimus, blanditiis quaerat aliquam, dicta reiciendis ducimus delectus voluptatem cumque necessitatibus illo nihil illum, unde sequi optio quasi itaque dolores doloribus labore! Dolore similique modi praesentium ipsam, aperiam libero sint aliquam! Nisi facilis aspernatur fuga deleniti fugiat provident molestias amet blanditiis nulla, maxime molestiae dolore incidunt sed eaque illo maiores magnam laboriosam adipisci. Sunt facilis fuga cum ratione doloremque assumenda delectus explicabo earum, ab id consectetur atque voluptates eveniet non sed beatae possimus voluptate dolor dicta nisi reprehenderit! Fugit fuga sapiente similique praesentium, ipsam nisi beatae quas eaque. Amet quos nihil officia iusto molestias laboriosam enim ipsum? Sunt dolorem odit nam eum sed blanditiis quas tempore quam aspernatur alias, officia, repellat q', 'Games', '2024-06-23'),
(17, 'marvels-spiderman2.jpeg', 'Marvels Spiderman', 15.40, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam distinctio enim rerum et numquam? Sapiente commodi cum placeat quod aperiam quibusdam voluptates nisi perferendis in, tempore quisquam eos eligendi provident beatae modi eum ullam, mollitia ipsam culpa totam rem suscipit perspiciatis similique minus. Dolor, neque sit. Ipsum provident, dolorem, saepe impedit iste voluptate dolorum, illum cupiditate inventore tenetur dicta! Odit iure eveniet, harum quod suscipit iusto sed ipsam fugiat, ipsa quis obcaecati non veniam itaque dolorum inventore. Voluptatibus ex praesentium eveniet quaerat, dignissimos quibusdam veritatis, modi error corrupti esse vel totam! Aperiam minima adipisci nemo libero quidem iure totam alias, provident nobis ducimus sapiente vel aliquam maxime unde temporibus rerum tempora, exercitationem ipsa. Dignissimos accusamus non unde obcaecati, cupiditate illo. Non, veritatis voluptatem, iste aperiam ratione mollitia eum quo quidem, consequatur illum dolores. Lab', 'Games', '2024-06-23'),
(18, 'microsoftSurfacePro6.png', 'Microsoft Surface Pro6', 3020.22, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, repellendus deserunt esse molestias ad perferendis? Enim similique soluta tempora porro molestiae unde illum eligendi adipisci natus sapiente perferendis cupiditate nam dolorem asperiores libero fugiat inventore voluptate facere, nisi omnis dicta. Est repellendus ipsa eaque repellat beatae laudantium? Esse laudantium repellat aspernatur! Animi ipsa excepturi, velit molestias et voluptatibus dolor amet. Nisi vitae perspiciatis incidunt, voluptas qui eligendi illum blanditiis atque explicabo ipsa quidem fugit aperiam enim, dicta optio et. Nobis pariatur optio, quaerat, repudiandae necessitatibus officiis consequuntur iste provident at totam fuga a eaque minima quo. Distinctio ducimus expedita nesciunt, repudiandae illum ipsum eius, quaerat minima officia iure ipsa laboriosam magni doloremque voluptatum. Et accusantium non, neque fugiat exercitationem obcaecati consequatur ullam! Accusamus iure, a cumque ratione magn', 'Laptops', '2024-06-23'),
(19, 'microsoftSurfacePro7.jpg', 'Microsoft Surface Pro7', 2350.50, 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque illo ipsam debitis, doloribus ullam pariatur natus asperiores maxime. Quos minus, consequuntur officiis dicta totam sunt, similique alias praesentium, ad sapiente doloremque placeat. Molestias rem doloribus tenetur labore veritatis voluptate incidunt. Earum aperiam repudiandae rem voluptates tenetur aliquam fugiat voluptas odit ratione sunt veniam perspiciatis voluptate, consectetur facere in, aspernatur itaque, reiciendis animi modi cupiditate cum mollitia. Praesentium, perferendis assumenda. Quam sit perferendis voluptatem quia aspernatur possimus eum debitis laboriosam veritatis doloribus libero nesciunt omnis maxime, quae a minus tempora voluptatibus, aut amet repellat dolor aperiam. Magni commodi sed ratione id voluptas quod doloremque cum distinctio sint iure. Sunt harum dolores ipsam ab ipsa vitae exercitationem repellat, architecto maxime sapiente fuga consequatur rem ullam alias natus totam a soluta autem pro', 'Laptops', '2024-06-23'),
(20, 'playstation5.jpg', 'Playstation 5', 580.22, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Architecto ipsum enim doloribus temporibus sequi? Corporis alias placeat saepe odit voluptatibus debitis laboriosam eligendi consequuntur nesciunt neque nostrum culpa excepturi nam itaque iure animi, quaerat voluptatum quisquam impedit blanditiis reprehenderit dignissimos sapiente. Provident repudiandae dolor, doloribus dolorem amet, nostrum voluptatum, culpa distinctio excepturi quibusdam impedit quisquam error in facilis. Nesciunt molestiae earum libero cum incidunt distinctio voluptatum temporibus sit nisi perspiciatis nam ut illum sapiente nihil, vel, blanditiis dignissimos. Molestias nobis veritatis asperiores sit eius quaerat dignissimos expedita nemo, quam provident placeat explicabo cumque culpa quasi aliquid sapiente quod magnam numquam natus esse sint. Suscipit amet ipsam est dicta? Adipisci pariatur delectus a veniam laborum? Hic quam, nobis, nostrum necessitatibus earum sunt distinctio quisquam voluptatum qui, conseq', 'Consoles', '2024-06-23'),
(21, 'Rehmie.jpg', 'Rehmie', 110.22, ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus et magni aperiam officia, voluptatem excepturi perspiciatis possimus nostrum sit. Velit libero placeat, voluptatem illum ipsa nihil tempore recusandae? Debitis fuga tenetur porro assumenda nesciunt obcaecati. Id iusto accusantium voluptas omnis facilis nostrum, quibusdam consequatur dicta mollitia dignissimos cumque, at vitae adipisci ipsum, esse excepturi. Vel ab voluptates, amet dolore, neque inventore quod doloremque in blanditiis aliquid qui nesciunt fuga. Voluptatum nulla velit repellendus modi sed possimus porro minima incidunt, eligendi aperiam esse obcaecati tempore, est impedit harum qui beatae quis voluptate illo suscipit cumque ipsa expedita repudiandae! Itaque fugit veniam debitis repudiandae quis cupiditate natus, iste dignissimos excepturi voluptas inventore, voluptates maiores vel nemo. Incidunt consectetur, asperiores omnis mollitia ut nam assumenda fuga maiores earum iure impedit quod ullam harum libero a ', 'Watches', '2024-06-23'),
(22, 'rich-dad-poor-dad.jpg', 'Rich Dad Poor Dad', 20.22, '   Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minima totam optio voluptate amet dolorem natus aut, doloremque omnis laborum, atque voluptates? Debitis, sunt. Dolores praesentium quibusdam blanditiis labore explicabo sint, unde vel doloremque placeat officia sed quisquam consequatur, similique aliquam quod id facilis ipsam, deleniti provident a voluptatibus architecto repellat. Eaque et, mollitia saepe, voluptates voluptas qui quaerat totam accusantium numquam quod officiis nesciunt incidunt animi iste nemo aperiam. Quia autem fuga quis architecto consequatur dicta quisquam, incidunt cumque. Quibusdam natus optio obcaecati? Veritatis iste, consectetur qui illum saepe fugit aliquam. Similique labore repellendus odit asperiores, possimus corporis perspiciatis beatae quos reiciendis alias nemo ad itaque ipsum exercitationem, dolore error amet quibusdam dolorum. Laboriosam dolorem maxime deleniti porro tenetur commodi omnis. Numquam autem eius praesentium, quasi nisi exercita', 'Books', '2024-06-23'),
(23, 'richest-man-in-Babylon.jpeg', 'Richest Man In Babylon', 12.20, 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut optio harum debitis, dicta rem cupiditate incidunt eos ducimus delectus amet architecto at nobis ab modi fugiat doloremque omnis nemo dolores nisi nostrum ipsa maiores consequuntur facere neque! Nostrum, quidem vitae labore explicabo nesciunt possimus ratione omnis non sed esse eius libero aperiam obcaecati dolorum dicta nihil, quaerat nulla accusamus consequuntur? Maxime officia minus suscipit voluptatum vero nobis, sunt inventore cum aliquam repudiandae maiores? Nobis ipsam sunt atque magnam eaque cum vitae soluta quasi aliquam beatae vero neque quam repellat fugit dolorum commodi rem, a repellendus similique. Fugit sed voluptates illum natus! Quae consequatur vero nemo blanditiis earum quis at totam quidem error fugit, sunt cupiditate beatae veritatis voluptas tempore hic! Pariatur, suscipit nemo nostrum illum ipsa eaque commodi. Quo, earum! Quisquam autem ipsa molestias? Doloribus, reiciendis ut? Mollitia unde sint volupt', 'Books', '2024-06-23'),
(24, 's23.jpeg', 'Samsung S23', 1900.22, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium corrupti minima modi ea enim pariatur quo temporibus nostrum sunt explicabo, saepe veritatis voluptates totam? Libero quos tempore incidunt at placeat animi quisquam ipsam labore accusantium eaque ea, rerum voluptatibus similique quis deserunt odio, quasi, saepe officiis dolores. Ad sunt at id cumque, voluptas sint error suscipit dignissimos sit vel ipsum minus beatae non modi consectetur odio distinctio magnam perferendis dolorem. Eligendi iure voluptatem consequuntur mollitia aut porro repellat quod laborum iusto beatae dicta suscipit illum hic, illo natus aliquam, quam voluptates laboriosam error cupiditate reprehenderit vel aperiam dignissimos consequatur. Alias vitae molestias et! Id eos amet sequi, dolores iure beatae possimus optio delectus in praesentium, nihil sit consectetur veniam. Qui, veritatis deleniti doloribus molestias, nulla fugit maxime tempore obcaecati, magnam cum esse consequatur veniam provident ', 'Phones', '2024-06-23'),
(25, 'samsungS22.jpeg', 'Samsung S22', 2210.22, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quia eaque consequuntur totam accusamus perferendis esse omnis dolore delectus, quae et alias eius pariatur molestiae reiciendis quibusdam quasi corporis suscipit recusandae facilis impedit? Deleniti iure voluptatem cupiditate? Amet est, qui optio tenetur saepe blanditiis soluta a perspiciatis! Saepe rem repellat ratione ipsa fugit molestias nulla in eos, beatae placeat facere reprehenderit, architecto temporibus corrupti dignissimos! Dolor pariatur dolore culpa totam praesentium fugiat ullam, maxime dicta eaque iusto cumque suscipit! Assumenda obcaecati ut aperiam, ipsa fugiat voluptatem! Culpa debitis veniam soluta vero quo minima inventore eaque nulla placeat magni libero amet nihil reiciendis ea, odit modi quas exercitationem beatae porro. Aliquam, temporibus tempore. Porro maiores sed non sunt, mollitia a fugiat nam nihil. Quaerat illum laboriosam fugiat voluptatem, mollitia vel soluta asperiores voluptas est eos magni quo.', 'Phones', '2024-06-23'),
(26, 't500-smart-watch.jpg', 'T500 Smart Watch', 90.22, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam odio laborum fugit expedita qui distinctio officiis excepturi, earum eum consequatur aperiam reprehenderit tempora eaque adipisci hic repudiandae commodi quisquam nam aliquid omnis. Reprehenderit, omnis quae. Voluptate, quaerat beatae, possimus magnam doloremque maiores provident reiciendis cumque mollitia ab, ea laboriosam molestiae! Voluptate eligendi vero mollitia earum ut iste minima ipsum ratione tempora, odit similique nemo sunt iure, architecto quo temporibus? Quasi quis, incidunt ratione atque ab sit aliquid eos soluta, culpa eius, odit velit. Provident recusandae aperiam maiores error similique expedita aut dolorum molestiae deserunt, sapiente sunt libero architecto laboriosam sequi! Animi in, impedit non nesciunt officiis consequuntur. Vel fuga repellendus ullam ducimus voluptatum! Exercitationem saepe quam vitae nobis, dolorum neque ut sunt consequuntur officia id ab sequi distinctio dolor velit magnam placeat ', 'Watches', '2024-06-23'),
(27, 'think-and-grow-rich.jpg', 'Think And Grow Rich', 22.20, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat, placeat illum! Qui temporibus, molestias fuga eius pariatur quae mollitia rerum, architecto excepturi, doloribus assumenda! Sunt enim perferendis nisi, doloremque molestiae, odit accusantium quasi quia perspiciatis officiis ex eius labore asperiores earum excepturi suscipit, numquam voluptate. Mollitia voluptatibus aspernatur temporibus molestiae doloremque eius inventore quod maiores aperiam nemo aut expedita consequuntur ducimus harum nisi itaque in quaerat, libero placeat deleniti ratione eaque veritatis ipsa error. Eligendi, minima provident alias iusto dolores, blanditiis qui voluptate ipsa consequuntur, suscipit in eaque exercitationem incidunt iure id unde! Molestias delectus, dolores quisquam labore nemo suscipit optio necessitatibus vero error esse modi voluptatibus cupiditate aspernatur, eveniet a nesciunt saepe consectetur aperiam voluptas enim dicta reiciendis. Provident nobis similique culpa ullam enim deleni', 'Books', '2024-06-23'),
(28, 'wwe-2k24.jpeg', 'WWE 2K24', 35.24, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae esse quam nostrum laudantium sapiente cupiditate nulla numquam sunt, nam eligendi consequuntur illum exercitationem iusto itaque officiis neque sed deleniti iure ad tempora aperiam voluptatibus, eaque reprehenderit nemo? Incidunt, sunt consectetur. Quae nulla asperiores reprehenderit et, facilis veniam sit beatae. Asperiores necessitatibus nam culpa nemo impedit error porro quas reiciendis, modi maxime nobis facilis voluptates officia nihil! Repellat veniam officia dicta, itaque quam, quidem eveniet iure reiciendis provident, quaerat necessitatibus nemo? Autem omnis distinctio voluptatum eum incidunt officiis quibusdam consectetur explicabo debitis. Neque dolore, deserunt enim quam soluta distinctio illum adipisci voluptas qui atque in inventore sint, minima nihil possimus mollitia! Sapiente veniam temporibus quos voluptatum deserunt, nihil est debitis perferendis cumque eaque harum numquam natus? Quisquam sequi, illo conse', 'Games', '2024-06-23'),
(29, 'xbox-series-X.jpg', 'Xbox Series X', 610.22, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deserunt dolorum rem dicta quaerat ipsa possimus repellendus. Perspiciatis, sed. Quo incidunt minus inventore non, nam dolor maxime molestias. Repudiandae velit voluptate debitis soluta vitae! Repudiandae ad illum dicta soluta, tempora sed minima, esse vitae delectus, enim id unde nam cum fuga nulla! Maiores cumque perspiciatis inventore natus distinctio ad, facere aliquid officiis quo quisquam. Tempore adipisci molestiae doloremque ratione obcaecati, commodi hic, cupiditate quibusdam repudiandae voluptatum numquam vel, minima assumenda quo? Cum, vitae? Accusantium deleniti possimus ratione fuga suscipit quas, non, impedit tenetur alias laboriosam ea esse qui commodi. Vel, veniam? Obcaecati magnam non aut eligendi. Impedit eaque vel neque rerum reprehenderit beatae debitis laudantium iusto sed quo laboriosam id deserunt ipsa alias cum dolorum esse, quod quibusdam pariatur praesentium ipsum maxime cupiditate doloremque expedita. ', 'Consoles', '2024-06-23');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
